/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SupportRouteImport } from "./routes/support";
import { Route as SosReceiverRouteImport } from "./routes/sos-receiver";
import { Route as SosRouteImport } from "./routes/sos";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as SafeSpacesRouteImport } from "./routes/safe-spaces";
import { Route as ReportRouteImport } from "./routes/report";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as PrivacyRouteImport } from "./routes/privacy";
import { Route as NotificationsRouteImport } from "./routes/notifications";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as HistoryRouteImport } from "./routes/history";
import { Route as HeatmapRouteImport } from "./routes/heatmap";
import { Route as GuardianRouteImport } from "./routes/guardian";
import { Route as DebugUsersRouteImport } from "./routes/debug-users";
import { Route as CircleRouteImport } from "./routes/circle";
import { Route as CheckInRouteImport } from "./routes/check-in";
import { Route as AddContactRouteImport } from "./routes/add-contact";
import { Route as IndexRouteImport } from "./routes/index";

const SupportRoute = SupportRouteImport.update({
  id: "/support",
  path: "/support",
  getParentRoute: () => rootRouteImport,
});
const SosReceiverRoute = SosReceiverRouteImport.update({
  id: "/sos-receiver",
  path: "/sos-receiver",
  getParentRoute: () => rootRouteImport,
});
const SosRoute = SosRouteImport.update({
  id: "/sos",
  path: "/sos",
  getParentRoute: () => rootRouteImport,
});
const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
});
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
});
const SafeSpacesRoute = SafeSpacesRouteImport.update({
  id: "/safe-spaces",
  path: "/safe-spaces",
  getParentRoute: () => rootRouteImport,
});
const ReportRoute = ReportRouteImport.update({
  id: "/report",
  path: "/report",
  getParentRoute: () => rootRouteImport,
});
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
});
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
});
const NotificationsRoute = NotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
});
const HistoryRoute = HistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => rootRouteImport,
});
const HeatmapRoute = HeatmapRouteImport.update({
  id: "/heatmap",
  path: "/heatmap",
  getParentRoute: () => rootRouteImport,
});
const GuardianRoute = GuardianRouteImport.update({
  id: "/guardian",
  path: "/guardian",
  getParentRoute: () => rootRouteImport,
});
const DebugUsersRoute = DebugUsersRouteImport.update({
  id: "/debug-users",
  path: "/debug-users",
  getParentRoute: () => rootRouteImport,
});
const CircleRoute = CircleRouteImport.update({
  id: "/circle",
  path: "/circle",
  getParentRoute: () => rootRouteImport,
});
const CheckInRoute = CheckInRouteImport.update({
  id: "/check-in",
  path: "/check-in",
  getParentRoute: () => rootRouteImport,
});
const AddContactRoute = AddContactRouteImport.update({
  id: "/add-contact",
  path: "/add-contact",
  getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AddContactRoute: AddContactRoute,
  CheckInRoute: CheckInRoute,
  CircleRoute: CircleRoute,
  DebugUsersRoute: DebugUsersRoute,
  GuardianRoute: GuardianRoute,
  HeatmapRoute: HeatmapRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReportRoute: ReportRoute,
  SafeSpacesRoute: SafeSpacesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SosRoute: SosRoute,
  SosReceiverRoute: SosReceiverRoute,
  SupportRoute: SupportRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
